### ISSUE TITLE
(Request) Sentis support and updated models

### ISSUE THREAD

**Issue by michaelj909** [keijiro/BodyPixSentis#10]
Hey, firstly thanks for the effort you've put into this project - it works great!

With Unity set to phase out Barracuda in favour of Sentis, are there currently any plans to update this project with Sentis support? As I said, it's a great asset, so it'd be a shame if it was rendered unusable by Unity's shift to Sentis.

Also, I was wondering if there are any plans to include updated or new models in the project? If not, do you have any advice for how I could adapt the project to support more models? I notice that some OBS plugins for example use things like RVM MobileNetV3 model and MediaPipe, among others, so I'm somewhat interested in how those models would perform in Unity.

Thanks again!

**Comment by keijiro** [comment]
By the way, isn't there anyone who ported BodyPix to Sentis other than me? I wonder if I should do this by myself.

**Comment by keijiro** [comment]
Done (3.0.0)
