### ISSUE TITLE
Getting started with Colored Masks

### ISSUE THREAD

**Issue by tugonbob** [keijiro/BodyPixSentis#9]
Apologizes for the ignorant question. I'm very new to Unity. 

I'm trying to implement the Colored Mask body segmentation in Unity. After installing the BodyPixBarracuda as per your README, what are the next steps?

I've tried your sample project and everything works perfectly. I'm just not sure how to change things to fit my needs.

Any help would be appreciated.

Thanks

**Comment by tugonbob** [comment]
I'm able to overlay the masks onto a webcam stream. However, I need some help retrieving the mask dimensions of a specific body part.

<img width="808" alt="Screenshot_2023-05-31_at_12 31 45_PM" src="https://github.com/keijiro/BodyPixBarracuda/assets/57576522/99e2f0b7-36df-4885-9a9f-29971de4d6b9">

How do I get the array of points of the shape of the LeftLowerLegFront and LeftLowerLegBack masks?

Thanks

**Comment by tugonbob** [comment]
Any update on this?

**Comment by keijiro** [comment]
No.

**Comment by keijiro** [comment]
Sorry but this issue tracker is dedicated to managing issues/bugs found in this package. I'd recommend learning shader coding to know how to generate masks from inference results of BodyPix.
